// <auto-generated />
using System;
using HRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMS.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRMS.Models.DailyPredictionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("RoomPrice");

                    b.HasKey("Id");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("HRMS.Models.DailyRoomRates", b =>
                {
                    b.Property<int>("DailyRoomRateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountTypeExclusive");

                    b.Property<int>("AmountTypeInclusive");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Iscomplimentary");

                    b.Property<string>("RateCode");

                    b.Property<int>("RateCodeId");

                    b.Property<bool>("RoomRateIsSet");

                    b.Property<string>("RoomTypeCode");

                    b.Property<int>("RoomTypeId");

                    b.Property<int>("TaxAmount");

                    b.HasKey("DailyRoomRateId");

                    b.ToTable("RoomRates");
                });
#pragma warning restore 612, 618
        }
    }
}
